config/routes.rb
# Custom resource provider
module ApiResource
  def api_resource(resource_name, opts = {}, &block)
    #opts = opts.merge(except: [])
    resources(resource_name, opts, &block)
    post "#{resource_name}/:id" => "#{resource_name}#update"
    post "#{resource_name}/search" => "#{resource_name}#search", as: "#{resource_name}_search"
  end
end
# Make available in routes.draw
ActionDispatch::Routing::Mapper.include(ApiResource)


Rails.application.routes.draw do

  get 'home/home'
  root  'books#index'

  resources :book_genres
  resources :genres do
    collection do
      post 'search'
    end
  end
  resources :goodreads_list_books
  resources :goodreads_lists
  resources :books do
    collection do
      get 'explore'
      post 'tags'
    end
  end

  namespace :api do
    api_resource :genres
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/goodreads_list.rb
class GoodreadsList < ApplicationRecord

	has_many :goodreads_list_books
	has_many :books, :through => :goodreads_list_books

	def import
		last_id = Book.last.id
		t1 = Time.now

		40.times do |page|
			response = HTTParty.get("https://www.goodreads.com/list/show/#{self.goodreads_id}?page=#{page + 1}")
			doc = Nokogiri::HTML(response.body)

			self.name ||= doc.css('h1')[0].text.strip rescue nil
			self.description ||= doc.css('h1+div')[0].text.sub(/flag$/, '').strip rescue nil

			trs = doc.css('#all_votes tr')

			break if trs.length == 0

			trs.each do |tr|
				book_url = tr.css('a.bookTitle').first['href']
				goodreads_id = book_url.split('/').last.to_i

				book = Book.where(goodreads_id: goodreads_id).first
				book ||= Book.create(goodreads_id: goodreads_id)

				GoodreadsListBook.create(
					goodreads_list_id: self.id,
					book_id: book.id,
					rank: tr.css('td.number').first.text.to_i,
					score: tr.css('a:contains("score")').first.text.gsub(/[^\d]/,'').to_i,
					voted: tr.css('a:contains("voted")').first.text.gsub(/[^\d]/,'').to_i
				)
			end

			sleep 5
		end

		self.imported_at = DateTime.now
		self.save

		Rails.logger.info "Imported #{Book.last.id - last_id}/#{self.goodreads_list_books.count} in #{Time.now - t1} seconds"
	end

end

app/controllers/goodreads_lists_controller.rb
class GoodreadsListsController < ApplicationController
	before_action :set_goodreads_list, only: %i[ show edit update destroy ]

	# GET /goodreads_lists or /goodreads_lists.json
	def index
		@goodreads_lists = GoodreadsList.all.page(params[:page] || 1).per(50)
	end

	# GET /goodreads_lists/1 or /goodreads_lists/1.json
	def show
		@genre_counts = {}

		@goodreads_list.books.joins(:genres).group('genres.id')
					.select('genres.name as genre_name, count(books.id) as genre_count')
					.each do |b|
						@genre_counts[b['genre_name']] = b['genre_count']
					end
	end

	# GET /goodreads_lists/new
	def new
		@goodreads_list = GoodreadsList.new
	end

	# GET /goodreads_lists/1/edit
	def edit
	end

	# POST /goodreads_lists or /goodreads_lists.json
	def create
		@goodreads_list = GoodreadsList.new(goodreads_list_params)

		respond_to do |format|
			if @goodreads_list.save
				format.html { redirect_to goodreads_list_url(@goodreads_list), notice: "Goodreads list was successfully created." }
				format.json { render :show, status: :created, location: @goodreads_list }
			else
				format.html { render :new, status: :unprocessable_entity }
				format.json { render json: @goodreads_list.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /goodreads_lists/1 or /goodreads_lists/1.json
	def update
		respond_to do |format|
			if @goodreads_list.update(goodreads_list_params)
				format.html { redirect_to goodreads_list_url(@goodreads_list), notice: "Goodreads list was successfully updated." }
				format.json { render :show, status: :ok, location: @goodreads_list }
			else
				format.html { render :edit, status: :unprocessable_entity }
				format.json { render json: @goodreads_list.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /goodreads_lists/1 or /goodreads_lists/1.json
	def destroy
		@goodreads_list.destroy

		respond_to do |format|
			format.html { redirect_to goodreads_lists_url, notice: "Goodreads list was successfully destroyed." }
			format.json { head :no_content }
		end
	end

	def import
		url = params[:url]
		goodreads_list_id = url.split('/').last.to_i

		list = GoodreadsList.where(goodreads_id: goodreads_list_id).first
		if list
			render json: list
			return
		end

		list = GoodreadsList.create(goodreads_id: goodreads_list_id)

		list.import

		render json: list
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_goodreads_list
			@goodreads_list = GoodreadsList.find(params[:id])
		end

		# Only allow a list of trusted parameters through.
		def goodreads_list_params
			params.require(:goodreads_list).permit(:goodreads_id, :name, :description)
		end
end

app/helpers/goodreads_lists_helper.rb
module GoodreadsListsHelper
end

app/views/goodreads_lists/_form.html.erb
<%= form_with(model: goodreads_list) do |form| %>
  <% if goodreads_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goodreads_list.errors.count, "error") %> prohibited this goodreads_list from being saved:</h2>

      <ul>
        <% goodreads_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :goodreads_id %>
    <%= form.number_field :goodreads_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goodreads_lists/edit.html.erb
<h1>Editing Goodreads List</h1>

<%= render 'form', goodreads_list: @goodreads_list %>

<%= link_to 'Show', @goodreads_list %> |
<%= link_to 'Back', goodreads_lists_path %>

app/views/goodreads_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goodreads Lists</h1>

<table>
  <thead>
    <tr>
      <th>Goodreads</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goodreads_lists.each do |goodreads_list| %>
      <tr>
        <td><%= goodreads_list.goodreads_id %></td>
        <td><%= goodreads_list.name %></td>
        <td><%= goodreads_list.description %></td>
        <td><%= link_to 'Show', goodreads_list %></td>
        <td><%= link_to 'Edit', edit_goodreads_list_path(goodreads_list) %></td>
        <td><%= link_to 'Destroy', goodreads_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goodreads List', new_goodreads_list_path %>

app/views/goodreads_lists/new.html.erb
<h1>New Goodreads List</h1>

<%= render 'form', goodreads_list: @goodreads_list %>

<%= link_to 'Back', goodreads_lists_path %>

app/views/goodreads_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goodreads:</strong>
  <%= @goodreads_list.goodreads_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @goodreads_list.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @goodreads_list.description %>
</p>

<%= link_to 'Edit', edit_goodreads_list_path(@goodreads_list) %> |
<%= link_to 'Back', goodreads_lists_path %>


<% if @genre_counts %>
  <% @genre_counts.keys.sort_by { |key| @genre_counts[key]  }.reverse.map do |key| %>
    <div class="row">
      <div class="col">
        <%=  key  %>
      </div>
      <div class="col">
        <%=  @genre_counts[key] %>
      </div>
    </div>
  <% end %>
<% end %>