config/routes.rb
# Custom resource provider
module ApiResource
  def api_resource(resource_name, opts = {}, &block)
    #opts = opts.merge(except: [])
    resources(resource_name, opts, &block)
    post "#{resource_name}/:id" => "#{resource_name}#update"
    post "#{resource_name}/search" => "#{resource_name}#search", as: "#{resource_name}_search"
  end
end
# Make available in routes.draw
ActionDispatch::Routing::Mapper.include(ApiResource)


Rails.application.routes.draw do

  get 'home/home'
  root  'books#index'

  resources :book_genres
  resources :genres do
    collection do
      post 'search'
    end
  end
  resources :goodreads_list_books
  resources :goodreads_lists
  resources :books do
    collection do
      get 'explore'
      post 'tags'
    end
  end

  namespace :api do
    api_resource :genres
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/controllers/book_genres_controller.rb
class BookGenresController < ApplicationController
  before_action :set_book_genre, only: %i[ show edit update destroy ]

  # GET /book_genres or /book_genres.json
  def index
    @book_genres = BookGenre.all
  end

  # GET /book_genres/1 or /book_genres/1.json
  def show
  end

  # GET /book_genres/new
  def new
    @book_genre = BookGenre.new
  end

  # GET /book_genres/1/edit
  def edit
  end

  # POST /book_genres or /book_genres.json
  def create
    @book_genre = BookGenre.new(book_genre_params)

    respond_to do |format|
      if @book_genre.save
        format.html { redirect_to book_genre_url(@book_genre), notice: "Book genre was successfully created." }
        format.json { render :show, status: :created, location: @book_genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_genres/1 or /book_genres/1.json
  def update
    respond_to do |format|
      if @book_genre.update(book_genre_params)
        format.html { redirect_to book_genre_url(@book_genre), notice: "Book genre was successfully updated." }
        format.json { render :show, status: :ok, location: @book_genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_genres/1 or /book_genres/1.json
  def destroy
    @book_genre.destroy

    respond_to do |format|
      format.html { redirect_to book_genres_url, notice: "Book genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_genre
      @book_genre = BookGenre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_genre_params
      params.require(:book_genre).permit(:book_id, :genre_id)
    end
end

app/helpers/book_genres_helper.rb
module BookGenresHelper
end

app/views/book_genres/_form.html.erb
<%= form_with(model: book_genre) do |form| %>
  <% if book_genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_genre.errors.count, "error") %> prohibited this book_genre from being saved:</h2>

      <ul>
        <% book_genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.text_field :book_id %>
  </div>

  <div class="field">
    <%= form.label :genre_id %>
    <%= form.text_field :genre_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_genres/edit.html.erb
<h1>Editing Book Genre</h1>

<%= render 'form', book_genre: @book_genre %>

<%= link_to 'Show', @book_genre %> |
<%= link_to 'Back', book_genres_path %>

app/views/book_genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Genres</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_genres.each do |book_genre| %>
      <tr>
        <td><%= book_genre.book_id %></td>
        <td><%= book_genre.genre_id %></td>
        <td><%= link_to 'Show', book_genre %></td>
        <td><%= link_to 'Edit', edit_book_genre_path(book_genre) %></td>
        <td><%= link_to 'Destroy', book_genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Genre', new_book_genre_path %>

app/views/book_genres/new.html.erb
<h1>New Book Genre</h1>

<%= render 'form', book_genre: @book_genre %>

<%= link_to 'Back', book_genres_path %>

app/views/book_genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @book_genre.book_id %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book_genre.genre_id %>
</p>

<%= link_to 'Edit', edit_book_genre_path(@book_genre) %> |
<%= link_to 'Back', book_genres_path %>