config/routes.rb
# Custom resource provider
module ApiResource
  def api_resource(resource_name, opts = {}, &block)
    #opts = opts.merge(except: [])
    resources(resource_name, opts, &block)
    post "#{resource_name}/:id" => "#{resource_name}#update"
    post "#{resource_name}/search" => "#{resource_name}#search", as: "#{resource_name}_search"
  end
end
# Make available in routes.draw
ActionDispatch::Routing::Mapper.include(ApiResource)


Rails.application.routes.draw do

  get 'home/home'
  root  'books#index'

  resources :book_genres
  resources :genres do
    collection do
      post 'search'
    end
  end
  resources :goodreads_list_books
  resources :goodreads_lists
  resources :books do
    collection do
      get 'explore'
      post 'tags'
    end
  end

  namespace :api do
    api_resource :genres
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/goodreads_list_book.rb
class GoodreadsListBook < ApplicationRecord
  belongs_to :book
  belongs_to :goodreads_list
end

app/controllers/goodreads_list_books_controller.rb
class GoodreadsListBooksController < ApplicationController
  before_action :set_goodreads_list_book, only: %i[ show edit update destroy ]

  # GET /goodreads_list_books or /goodreads_list_books.json
  def index
    @goodreads_list_books = GoodreadsListBook.all.page(params[:page] || 1).per(50)
  end

  # GET /goodreads_list_books/1 or /goodreads_list_books/1.json
  def show
  end

  # GET /goodreads_list_books/new
  def new
    @goodreads_list_book = GoodreadsListBook.new
  end

  # GET /goodreads_list_books/1/edit
  def edit
  end

  # POST /goodreads_list_books or /goodreads_list_books.json
  def create
    @goodreads_list_book = GoodreadsListBook.new(goodreads_list_book_params)

    respond_to do |format|
      if @goodreads_list_book.save
        format.html { redirect_to goodreads_list_book_url(@goodreads_list_book), notice: "Goodreads list book was successfully created." }
        format.json { render :show, status: :created, location: @goodreads_list_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @goodreads_list_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goodreads_list_books/1 or /goodreads_list_books/1.json
  def update
    respond_to do |format|
      if @goodreads_list_book.update(goodreads_list_book_params)
        format.html { redirect_to goodreads_list_book_url(@goodreads_list_book), notice: "Goodreads list book was successfully updated." }
        format.json { render :show, status: :ok, location: @goodreads_list_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @goodreads_list_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goodreads_list_books/1 or /goodreads_list_books/1.json
  def destroy
    @goodreads_list_book.destroy

    respond_to do |format|
      format.html { redirect_to goodreads_list_books_url, notice: "Goodreads list book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goodreads_list_book
      @goodreads_list_book = GoodreadsListBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def goodreads_list_book_params
      params.require(:goodreads_list_book).permit(:rank, :book_id, :goodreads_list_id, :score, :voted)
    end
end

app/helpers/goodreads_list_books_helper.rb
module GoodreadsListBooksHelper
end

app/views/goodreads_list_books/_form.html.erb
<%= form_with(model: goodreads_list_book) do |form| %>
  <% if goodreads_list_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goodreads_list_book.errors.count, "error") %> prohibited this goodreads_list_book from being saved:</h2>

      <ul>
        <% goodreads_list_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rank %>
    <%= form.number_field :rank %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.text_field :book_id %>
  </div>

  <div class="field">
    <%= form.label :goodreads_list_id %>
    <%= form.text_field :goodreads_list_id %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="field">
    <%= form.label :voted %>
    <%= form.number_field :voted %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goodreads_list_books/edit.html.erb
<h1>Editing Goodreads List Book</h1>

<%= render 'form', goodreads_list_book: @goodreads_list_book %>

<%= link_to 'Show', @goodreads_list_book %> |
<%= link_to 'Back', goodreads_list_books_path %>

app/views/goodreads_list_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goodreads List Books</h1>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Book</th>
      <th>Goodreads list</th>
      <th>Score</th>
      <th>Voted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goodreads_list_books.each do |goodreads_list_book| %>
      <tr>
        <td><%= goodreads_list_book.rank %></td>
        <td><%= goodreads_list_book.book_id %></td>
        <td><%= goodreads_list_book.goodreads_list_id %></td>
        <td><%= goodreads_list_book.score %></td>
        <td><%= goodreads_list_book.voted %></td>
        <td><%= link_to 'Show', goodreads_list_book %></td>
        <td><%= link_to 'Edit', edit_goodreads_list_book_path(goodreads_list_book) %></td>
        <td><%= link_to 'Destroy', goodreads_list_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goodreads List Book', new_goodreads_list_book_path %>

app/views/goodreads_list_books/new.html.erb
<h1>New Goodreads List Book</h1>

<%= render 'form', goodreads_list_book: @goodreads_list_book %>

<%= link_to 'Back', goodreads_list_books_path %>

app/views/goodreads_list_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rank:</strong>
  <%= @goodreads_list_book.rank %>
</p>

<p>
  <strong>Book:</strong>
  <%= @goodreads_list_book.book_id %>
</p>

<p>
  <strong>Goodreads list:</strong>
  <%= @goodreads_list_book.goodreads_list_id %>
</p>

<p>
  <strong>Score:</strong>
  <%= @goodreads_list_book.score %>
</p>

<p>
  <strong>Voted:</strong>
  <%= @goodreads_list_book.voted %>
</p>

<%= link_to 'Edit', edit_goodreads_list_book_path(@goodreads_list_book) %> |
<%= link_to 'Back', goodreads_list_books_path %>